services:
  coco-downloader:
    image: markcxx/coco-downloader:latest
    container_name: coco-downloader
    restart: unless-stopped
    environment:
      - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
